function [ Core ] = extract_selected_design_data ( Wave )
if Wave.Inductor.IndToBeDesigned == 0
    Core.Nmax_p = Wave.Inductor.Lg_Design.Core_Nmax_p ;
    Core.CoreType = Wave.Inductor.Lg_Design.CoreType ;
    Core.Wire.CondMat= Wave.Inductor.Lg_Design.Wire_Material ;
    Core.MaterialType = Wave.Inductor.Lg_Design.MaterialType ;
    Core.k_stack = Wave.Inductor.Lg_Design.NumberfoStack;
    Core.N = Wave.Inductor.Lg_Design.NumberofTurns ;
    Core.CorePart = Wave.Inductor.Lg_Design.CorePart;
    Core.NumberfoStack = Wave.Inductor.Lg_Design.NumberfoStack;
    Core.OD = Wave.Inductor.Lg_Design.Core_OD;  % [m] External Core Diameter
    Core.ID = Wave.Inductor.Lg_Design.Core_ID;  % [m] Internal Core Diameter
    Core.HT = Wave.Inductor.Lg_Design.Core_HT;  % [m] Height of Core
    Core.e = Wave.Inductor.Lg_Design.Core_e;               % [m] Winding to Core gap
    Core.Core_Volume = Wave.Inductor.Lg_Design.Core_Volume;
    Core.le = Wave.Inductor.Lg_Design.Wire_le;% [m] Magnetic Path Length
    Core.Ae = Wave.Inductor.Lg_Design.Wire_Ae;
    Core.Aw = Wave.Inductor.Lg_Design.Wire_Aw;%Window Area
    Core.Core_Weight = Wave.Inductor.Lg_Design.Core_Weight; %[kg]
    Core.lg = 0;
    Core.Wire.d_ISO = 0.1e-3;  % [m] Wire Isolation Distances
    Core.Wire.fill = 0.8;      % [m] Fill factor of Litz Wire
    Core.e = 1e-3;            % [m] Bobine Distance to Core
    Core.Wire.AWGPart = Wave.Inductor.Lg_Design.Wire_AWGPart ;
    Core.Wire.d_strand = Wave.Inductor.Lg_Design.Wire_d_strand ;
    Core.Wire.d_wire = Wave.Inductor.Lg_Design.Wire_Diameter;
    Core.Wire.Turn_Length = Wave.Inductor.Lg_Design.Core_Wire_Turn_Length;
    Core.Wire.n_strand = Wave.Inductor.Lg_Design.Wire_n_strand ;
    Core.Wire.CondVolume = Wave.Inductor.Lg_Design.Wire_volume;
    Core.Wire_Weight = Wave.Inductor.Lg_Design.Wire_Weight;
    Core.Result.Total_Weight = Wave.Inductor.Lg_Design.Total_Weight;
else 
    Core.Nmax_p = Wave.Inductor.Lc_Design.Core_Nmax_p ;
    Core.CoreType = Wave.Inductor.Lc_Design.CoreType ;
    Core.Wire.CondMat= Wave.Inductor.Lc_Design.Wire_Material ;
    Core.MaterialType = Wave.Inductor.Lc_Design.MaterialType ;
    Core.k_stack = Wave.Inductor.Lg_Design.NumberfoStack;
    Core.N = Wave.Inductor.Lg_Design.NumberofTurns ;
    Core.CorePart = Wave.Inductor.Lc_Design.CorePart;
    Core.NumberfoStack = Wave.Inductor.Lc_Design.NumberfoStack;
    Core.OD = Wave.Inductor.Lc_Design.Core_OD;  % [m] External Core Diameter
    Core.ID = Wave.Inductor.Lc_Design.Core_ID;  % [m] Internal Core Diameter
    Core.HT = Wave.Inductor.Lc_Design.Core_HT;  % [m] Height of Core
    Core.e = Wave.Inductor.Lc_Design.Core_e;               % [m] Winding to Core gap
    Core.Core_Volume = Wave.Inductor.Lc_Design.Core_Volume;
    Core.le = Wave.Inductor.Lc_Design.Wire_le;% [m] Magnetic Path Length
    Core.Ae = Wave.Inductor.Lc_Design.Wire_Ae;
    Core.Aw = Wave.Inductor.Lc_Design.Wire_Aw;%Window Area
    Core.Core_Weight = Wave.Inductor.Lc_Design.Core_Weight; %[kg]
    Core.lg = 0;
    Core.Wire.d_ISO = 0.1e-3;  % [m] Wire Isolation Distances
    Core.Wire.fill = 0.8;      % [m] Fill factor of Litz Wire
    Core.e = 1e-3;            % [m] Bobine Distance to Core
    Core.Wire.AWGPart = Wave.Inductor.Lc_Design.Wire_AWGPart ;
    Core.Wire.d_strand = Wave.Inductor.Lc_Design.Wire_d_strand ;
    Core.Wire.d_wire = Wave.Inductor.Lc_Design.Wire_Diameter;
    Core.Wire.Turn_Length = Wave.Inductor.Lc_Design.Core_Wire_Turn_Length;
    Core.Wire.n_strand = Wave.Inductor.Lc_Design.Wire_n_strand ;
    Core.Wire.CondVolume = Wave.Inductor.Lc_Design.Wire_volume;
    Core.Wire_Weight = Wave.Inductor.Lc_Design.Wire_Weight;
    Core.Result.Total_Weight = Wave.Inductor.Lc_Design.Total_Weight;
end